from flask import Flask, render_template
app = Flask(__name__)

from sqlalchemy import create_engine
from sqlalchemy.orm import sessionmaker
from database_setup import Base, CatalogCategory, CategoryItem

engine = create_engine('sqlite:///catalog.db')
Base.metadata.bind = engine
DBSession = sessionmaker(bind=engine)
session = DBSession()
session.query(CategoryItem).delete()
session.query(CatalogCategory).delete()

accessories = CatalogCategory(name = "accessories")
session.add(accessories)
session.commit()
helmet = CatalogCategory(name = "helmets")
session.add(helmet)
session.commit()
gloves = CatalogCategory(name = "gloves")
session.add(gloves)
session.commit()
chest = CatalogCategory(name = "chests")
session.add(chest)
session.commit()
belts = CatalogCategory(name = "belts")
session.add(belts)
session.commit()
pants = CatalogCategory(name = "pants")
session.add(pants)
session.commit()
shoes = CatalogCategory(name = "shoes")
session.add(shoes)
session.commit()

accessory1 = CategoryItem(title = "Silver Ring", category_id = 1, description = "Made of silver. Found in the bottomless sea.", user = "ori")
session.add(accessory1)
session.commit()
accessory2 = CategoryItem(title = "Jeweled Gold Necklace", category_id = 1, description = "Made of gold, has assorted jewels. Said to be found in an ancient crypt.", user = "ori")
session.add(accessory2)
session.commit()
helmet1 = CategoryItem(title = "Cone Helm", category_id = 2, description = "Safety first with this smoothly domed helmet!", user = "ori")
session.add(helmet1)
session.commit()
helmet2 = CategoryItem(title = "Tricorn", category_id = 2, description = "Stylish and seafaring!", user = "ori")
session.add(helmet2)
session.commit()
helmet3 = CategoryItem(title = "Leather Cap", category_id = 2, description = "Simple is sometimes best!", user = "ori")
session.add(helmet3)
session.commit()
glove1 = CategoryItem(title = "Gauntlet", category_id = 3, description = "Metal glove that protects all parts of the hand!", user = "ori")
session.add(glove1)
session.commit()
glove2 = CategoryItem(title = "Neon Glove", category_id = 3, description = "So bright it'll catch anyone's attention!", user = "ori")
session.add(glove2)
session.commit()
glove3 = CategoryItem(title = "Glove Glove", category_id = 3, description = "A glove in a glove.", user = "ori")
session.add(glove3)
session.commit()
chest1 = CategoryItem(title = "Platemail", category_id = 4, description = "Plated with plates of assorted sizes. One size fits all!", user = "ori")
session.add(chest1)
session.commit()
chest2 = CategoryItem(title = "Embezzled Suit", category_id = 4, description = "Sparkly and dazzling.", user = "ori")
session.add(chest2)
session.commit()
belt1 = CategoryItem(title = "Cord of Potential", category_id = 5, description = "Limitless uses!", user = "ori")
session.add(belt1)
session.commit()
belt2 = CategoryItem(title = "Crystal Belt", category_id = 5, description = "Dozens of colors, endless length.", user = "ori")
session.add(belt2)
session.commit()
pant1 = CategoryItem(title = "Steel Pants", category_id = 6, description = "A bit stiff to move in. Factory crafted.", user = "ori")
session.add(pant1)
session.commit()
shoe1 = CategoryItem(title = "Rainbow Boots", category_id = 7, description = "Add a bit of color to your step!", user = "ori")
session.add(shoe1)
session.commit()
shoe2 = CategoryItem(title = "Sneaker Boots", category_id = 7, description = "Possibly interesting. Not that good at sneaking.", user = "ori")
session.add(shoe2)
session.commit()
